#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

SAYINGS=(
    "So long and thanks for all the fish!\n  -- Douglas Adams"
    "Good morning! And in case I don't see ya, good afternoon, good evening and goodnight.\n  --Truman Burbank"
    "It is a mistake to think you can solve any major problems just with potatoes.\n  -- Douglas Adams"
    "Nothing travels faster than the speed of light with the possible exception of bad news, which obeys its own special laws.\n  -- Douglas Adams"
    "Don't panic.\n  -- Douglas Adams"
    "“Funny,” he intoned funerally, “how just when you think life can’t possibly get any worse it suddenly does.”\n  -- Douglas Adams"
)

# Print a randomly-chosen message:
echo $SAYINGS[$(($RANDOM % ${#SAYINGS} + 1))]

} >&2
