#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

SAYINGS=(
    "“So long and thanks for all the fish!”\n  -- Douglas Adams"
    "“Good morning! And in case I don't see ya, good afternoon, good evening and goodnight.”\n  --Truman Burbank"
    "“It is a mistake to think you can solve any major problems just with potatoes.”\n  -- Douglas Adams"
    "“Nothing travels faster than the speed of light with the possible exception of bad news, which obeys its own special laws.”\n  -- Douglas Adams"
    "“DON'T PANIC.”\n  -- Douglas Adams"
    "“Funny,” he intoned funerally, “how just when you think life can’t possibly get any worse it suddenly does.”\n  -- Douglas Adams"
    "“This must be Thursday,' said Arthur to himself, sinking low over his beer. 'I never could get the hang of Thursdays.”\n  -- Douglas Adams"
    "“The ability to speak does not make you intelligent.”\n -- George Lucas"
    "“That's what I do. I drink, and I know things”\n -- Tyrion Lannister (George R. R. Martin)"
    "“Hodor? Hodor.”\n -- Hodor (George R. R. Martin)"
    "“Time is an illusion. Lunchtime doubly so.”\n -- Douglas Adams"
    "“Would it save you a lot of time if I just gave up and went mad now?”\n -- Douglas Adams"
    "“For a moment, nothing happened. Then, after a second or so, nothing continued to happen.”\n -- Douglas Adams"
    "“We demand rigidly defined areas of doubt and uncertainty!”\n -- Douglas Adams"
    "“Perhaps I'm old and tired, but I always think that the chances of finding out what really is going on are so absurdly remote that the only thing to do is to say hang the sense of it and just keep yourself occupied.”\n -- Douglas Adams"
    "“and we’ll be saying a big hello to all intelligent life forms everywhere … and to everyone else out there, the secret is to bang the rocks together, guys.”\n -- Douglas Adams"
    "“Ow! My brains!”\n -- Douglas Adams"
    "“The Ultimate Answer to Life, The Universe and Everything is … 42!”\n -- Douglas Adams"
    "“Ford carried on counting quietly. This is about the most aggressive thing you can do to a computer, the equivalent of going up to a human being and saying \"Blood...blood...blood...blood...\"” \n -- Douglas Adams"
    "“I like the cover,\" he said. \"Don't Panic. It's the first helpful or intelligible thing anybody's said to me all day.”\n -- Douglas Adams"
    "“If they don’t keep exercising their lips, he thought, their brains start working.”\n -- Douglas Adams"
    "“I think the problem, to be quite honest with you, is that you've never actually known what the question is.”\n -- Douglas Adams"
    "“The mere thought hadn't even begun to speculate about the merest possibility of crossing my mind.”\n -- Douglas Adams"
    "“Only by counting could humans demonstrate their independence of computers.”\n -- Douglas Adams"
    "“Please relax,\" said the voice pleasantly, like a stewardess in an airliner with only one wing and two engines one of which is on fire, \"you are perfectly safe.”\n -- Douglas Adams"
    "“…to boldly split infinitives that no man had split before…”\n -- Douglas Adams"
    "“It gives me my headache just trying to think down to your level”\n -- Douglas Adams"
    "“Anything that happens, happens.”\n -- Douglas Adams"
    "“One of the things Ford Prefect had always found hardest to understand about humans was their habit of continually stating and repeating the very very obvious.”\n -- Douglas Adams"
    "“It is an important and popular fact that things are not always what they seem.”\n -- Douglas Adams"
    "“Arthur’s mind was beginning to reassemble itself from the shell-shocked fragments the previous day had left him with.”\n -- Douglas Adams"
    "“One thing\" he further added \"has suddenly ceased to lead to another”\n -- Douglas Adams"
    "“I’m afraid you’re going to have to accept it.”\n -- Douglas Adams"
    "“The knack of flying is learning how to throw yourself at the ground and miss”\n -- Douglas Adams"
    "“I love deadlines. I like the whooshing sound they make as they fly by.“\n -- Douglas Adams"
    "“The scholar's greatest weakness: calling procrastination research.”\n — Stephen King"
    "“La peur fait faire des affaires qui n'ont pas de criss de bon sens.”\n — Horacio Aruda"
    "“Habituellement, quand on s'assoit sur un banc, on ne le liche pas.”\n — Horacio Aruda"

)

# Print a randomly-chosen message:
echo $SAYINGS[$(($RANDOM % ${#SAYINGS} + 1))]

} >&2
